### ISSUE TITLE
How to save the trained model and load the saved model?

### ISSUE THREAD

**Issue by CaptainXudui** [hibayesian/spark-fm#1]
Hi ,hibayesian !Thanks a lot for spark-fm sharing.I have checked the sample code which uses model=train.fit(trainData) and model.transform(testData) for prediction. 
My concern is that how can I save the trained model in local txt and load it in future use.
I only found the related weight of the model but the weight can not  be reloaded directly as model.
Looking forward to your concern and feedback.Thanks.

**Comment by hibayesian** [comment]
Hi, sjtuxiaoming. 

If you'd like to save and load a model, you just need to make sure that the `FactorizationMachinesModel` extend MLWritable and MLReadable interfaces and implement write and load methods.

**Comment by hibayesian** [comment]
Hi, sjtuxiaoming.

If you'd like to save and load a model, you just need to make sure that the FactorizationMachinesModel extend MLWritable and MLReadable interfaces and implement write and load methods.

**Comment by CaptainXudui** [comment]
Thanks hibayesian. By now I can use the model.weight to calculate the score for new test sample. Maybe I will implement the write and load methods later .But if you can update the write and load methods will be better.Thanks again
