### ISSUE TITLE
Fatal Bug need to fix

### ISSUE THREAD

**Issue by codlife** [hibayesian/spark-fm#5]
1. Bug1
in FactorizationMachinesUpdater, need to use the below code, otherwise, SGD will exist with only 1 iteration.
val weightsNew = weightsOld.copy.toArray

2. Bug2
in FactorizationMachinesGradient, change the code below, for the loss calculation.
//      case Algo.BinaryClassification => -Math.log(1 + 1 / (1 + Math.exp(-p * label)))
      case Algo.BinaryClassification => Math.log(1 + Math.exp(-p * label))
@hibayesian

**Comment by hibayesian** [comment]
@codlife 

Thanks for pointing that out. Will fix them soon. :-)
